### ISSUE TITLE
Error with signing in to a webmail site

### ISSUE THREAD

**Issue by ghost** [marius-wieschollek/passwords-webextension#109] opened 2020-12-17 08:22 UTC
When signing into https://runbox.com/app/login, the auto-fill feature fails.  Also, individually selecting and pasting the username and password fields also fails.  The username and password both look correct, and if I delete and then replace the last letter of the username and password, the login works.  Any idea what is going on in this case?

**Comment by marius-wieschollek** [comment] 2020-12-19 16:02
It looks like they're using Angular. With this web-framework, it can happen that the data of the input field is updated, but the website does not realize this and still uses the previous value. 
This happens because Angular is waiting for an event that is not triggered when the value is updated programmatically.
If you add and remove a character, it will trigger that event and the issue is "solved".

The nightly version of the extension tries to bypass this issue by triggering the related event itself. If you're feeling adventurous, you can [install the nightly version](https://github.com/marius-wieschollek/passwords-webextension/wiki/nightly-builds) and see if the issue is fixed.

**Comment by JonathanGallagher** [comment] 2020-12-19 17:49
Thank you!

**Comment by marius-wieschollek** [comment] 2021-01-04 21:25
Does this issue still exist with v2 of the extension?

**Comment by marius-wieschollek** [comment] 2021-01-09 14:35
I will close this in favor of #122

**Closed** 2021-01-09 14:36 UTC
Labels: bug
