### ISSUE TITLE
passlink does not work 

### ISSUE THREAD

**Issue by dcrobertson01** [marius-wieschollek/passwords-webextension#220] opened 2022-03-07 00:56 UTC
### System Information
- Extension Version:
- App Version:
- Browser and Version:
- Client OS and Version:

### Steps to reproduce
1. Install extension on Vivaldi browser
2. open app in browser
3. go to more -> connect with passlink
4. click connect via link
5. extensions page on passlink.org that says I need the functionality of the extension, and has links to extension

### Expected result
set up extension
### Actual result
not set up extension
### Browser log
<details>
<summary>Browser log</summary>

```
background.js:2 Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    at I (background.js:2:760819) Object Error: Could not establish connection. Receiving end does not exist.
    at I (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:760819)
_addError @ background.js:2
background.js:2 PasswordsClient not found Error: PasswordsClient not found
    at Object.findById (background.js:2:802864)
    at async Object.getDefaultApi (background.js:2:785108)
    at async Object._getSettingsRepository (background.js:2:882958)
    at async Object._getServerSetting (background.js:2:882800)
    at async Object._serverGet (background.js:2:882153)
    at async Object.get (background.js:2:881137)
    at async Object.get (background.js:2:841981)
    at async Object.init (background.js:2:883698)
    at async Object.init (background.js:2:885470) Object Error: PasswordsClient not found
    at Object.findById (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:802864)
    at async Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:785108)
    at async Object._getSettingsRepository (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:882958)
    at async Object._getServerSetting (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:882800)
    at async Object._serverGet (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:882153)
    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:881137)
    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:841981)
    at async Object.init (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:883698)
    at async Object.init (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:885470)
_addError @ background.js:2
background.js:2 No default configured Error: No default configured
    at Object.getDefaultApi (background.js:2:785271)
    at async Object._getSettingsRepository (background.js:2:882958)
    at async Object._getServerSetting (background.js:2:882800)
    at async Object._serverGet (background.js:2:882153)
    at async Object.get (background.js:2:881137)
    at async Object.get (background.js:2:841981)
    at async Object.init (background.js:2:883698)
    at async Object.init (background.js:2:885470) Object Error: No default configured
    at Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:785271)
    at async Object._getSettingsRepository (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:882958)
    at async Object._getServerSetting (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:882800)
    at async Object._serverGet (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:882153)
    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:881137)
    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:841981)
    at async Object.init (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:883698)
    at async Object.init (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:885470)
_addError @ background.js:2
background.js:2 Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    at I (background.js:2:760819) Object Error: Could not establish connection. Receiving end does not exist.
    at I (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:760819)
_addError @ background.js:2
background.js:2 No tab with id: 96. Error: No tab with id: 96.
    at background.js:2:758304 Object Error: No tab with id: 96.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:758304
_addError @ background.js:2
background.js:2 PasswordsClient not found Error: PasswordsClient not found
    at Object.findById (background.js:2:802864)
    at async Object.getDefaultApi (background.js:2:785108)
    at async d.execute (DebugExtensionInfo.js:1:568)
    at async Object._executeController (background.js:2:874601)
    at async Array.<anonymous> (background.js:2:871983)
    at async Object._notifyListeners (background.js:2:833251)
    at async Object._processMessage (background.js:2:832838)
    at async Object._processReceivedMessage (background.js:2:831886) Object Error: PasswordsClient not found
    at Object.findById (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:802864)
    at async Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:785108)
    at async d.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/DebugExtensionInfo.js:1:568)
    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:874601)
    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:871983)
    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:833251)
    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832838)
    at async Object._processReceivedMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:831886)
_addError @ background.js:2
background.js:2 PasswordsClient not found Error: PasswordsClient not found
    at Object.findById (background.js:2:802864)
    at async Object.getDefaultApi (background.js:2:785108)
    at async d.execute (DebugExtensionInfo.js:1:568)
    at async Object._executeController (background.js:2:874601)
    at async Array.<anonymous> (background.js:2:871983)
    at async Object._notifyListeners (background.js:2:833251)
    at async Object._processMessage (background.js:2:832838)
    at async Object._processReceivedMessage (background.js:2:831886) Object Error: PasswordsClient not found
    at Object.findById (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:802864)
    at async Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:785108)
    at async d.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/DebugExtensionInfo.js:1:568)
    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:874601)
    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:871983)
    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:833251)
    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832838)
    at async Object._processReceivedMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:831886)
_addError @ background.js:2
background.js:2 No default configured Error: No default configured
    at Object.getDefaultApi (background.js:2:785271)
    at async d.execute (DebugExtensionInfo.js:1:568)
    at async Object._executeController (background.js:2:874601)
    at async Array.<anonymous> (background.js:2:871983)
    at async Object._notifyListeners (background.js:2:833251)
    at async Object._processMessage (background.js:2:832838)
    at async Object._processReceivedMessage (background.js:2:831886) Object Error: No default configured
    at Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:785271)
    at async d.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/DebugExtensionInfo.js:1:568)
    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:874601)
    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:871983)
    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:833251)
    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832838)
    at async Object._processReceivedMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:831886)
_addError @ background.js:2
background.js:2 No default configured Error: No default configured
    at Object.getDefaultApi (background.js:2:785271)
    at async d.execute (DebugExtensionInfo.js:1:568)
    at async Object._executeController (background.js:2:874601)
    at async Array.<anonymous> (background.js:2:871983)
    at async Object._notifyListeners (background.js:2:833251)
    at async Object._processMessage (background.js:2:832838)
    at async Object._processReceivedMessage (background.js:2:831886) Object Error: No default configured
    at Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:785271)
    at async d.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/DebugExtensionInfo.js:1:568)
    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:874601)
    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:871983)
    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:833251)
    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832838)
    at async Object._processReceivedMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:831886)
_addError @ background.js:2
```
</details>

**Comment by marius-wieschollek** [comment] 2022-08-23 18:51
Can you please fill in browser and extension info?

**Comment by Neonunux** [comment] 2022-09-27 11:19
due to this bug :
https://git.mdns.eu/nextcloud/passwords-webextension/-/blob/master/src/vue/Components/Accounts/Account.vue#L27
`pattern="([A-Za-z0-9]{5}-?){5}"`

code format is `xxxx-xxxx-xxxx-xxxx`

`pattern="([A-Za-z0-9]{4}-?){4}"`

**Comment by marius-wieschollek** [comment] 2023-03-21 11:05
@dcrobertson01 I can't reproduce the issue with the latest version of the extension and Vivaldi on [our test server](https://test.passwordsapp.org/info.html), so i'm closing the ticket.

@Neonunux It seems that you're trying to use the confirmation code as a token. That's not how this works, please follow the described steps in the Nextcloud dialog.

**Closed by marius-wieschollek** 2023-03-21 11:05 UTC
Labels: bug
