### ISSUE TITLE
Status Code 405 Method Not Allowed on update password (request method PATCH)

### ISSUE THREAD

**Issue by berturion** [marius-wieschollek/passwords-webextension#12] opened 2018-05-18 05:05 UTC
Hello,

Nextcloud 13.0.2
Php 7.2.5
Nginx : nginx-mainline 1.13.12-1
Firefox 60.0
Arch Linux 64
Nextcloud Passwords Client 1.5.0
Nextcloud Passwords App 2018.5.2

When Nextcloud Passwords Client detects a password change, the browser shows a notification to update the password. When I click on it, another notification says that password update failed.

When activating debugging on the Nextcloud Password Client (firefox extension), I see the failed request.

Here are the request headers (I replaced my host name)

Url is: https://myhost.mydomain.tld/index.php/apps/passwords/api/0.1/passwords/722

```
Host: myhost.mydomain.tld
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain, */*
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
authorization: Basic Ym...blablablablabla
content-type: application/json
origin: moz-extension://8d55e17a-79e7-4b21-9567-96d446690ee8
Content-Length: 167
DNT: 1
Connection: keep-alive
```

Here are the response headers:
```
HTTP/2.0 405 Method Not Allowed
server: nginx
date: Fri, 18 May 2018 04:42:44 GMT
content-type: text/html; charset=UTF-8
x-powered-by: PHP/7.2.5
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
set-cookie: oc_sessionPassphrase=NuuMV4...blablablablabla; path=/; secure; HttpOnly
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'nonce-...blablablablabla='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
x-frame-options: SAMEORIGIN
set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
set-cookie: ocr0uzgqnx0t=...blablablablabla; path=/; secure; HttpOnly
set-cookie: cookie_test=test; expires=Fri, 18-May-2018 05:42:44 GMT; Max-Age=3600
X-Firefox-Spdy: h2
```

I think the problem is that request method:PATCH returns 405 Method Not Allowed.

I followed the official Nextcloud guide to configure my nginx server. I don't know how to allow PATCH request and where to enable it (nginx, php, nextcloud) ?

**Comment by berturion** [comment] 2018-05-18 05:12
These are je JSON parameters of the PATCH request:

```
address: https://myhost.mydomain.tld/login
category: 0
datechanged: 2018-4-18
id: 722
loginname: mylogin
notes:  
pass: mypassword
website: myhost.mydomain.tld

```

**Comment by marius-wieschollek** [comment] 2018-05-18 08:47
The PATCH request is usually supported out of the box.
Could it be that you deleted the password in question? In that case it could be that the webextension still has the old password in its local database and will try to update it. Trying to update a password that does not exist will result in a 405 error, because the method PATCH is not allowed on a nonexisting entry.
The quickest way to check that would be to refresh the extension manually by clicking on the refresh icon in the upper right corner and then trying to save the password again.

**Comment by berturion** [comment] 2018-05-18 09:32
I see the password in the password list in Nextcloud and it appears in the Nextcloud Passwords Client after manual update. I tried to update multiple passwords and the update never worked. Creation works thow but I suppose it is not a PATCH request.

You think that I must investigate my nginx config ? Do you know how to explicitely enable PATCH method ?

I tried to add this in the server block and the php location block:

    add_header "Access-Control-Allow-Origin"  *;
    add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, HEAD, PUT, DELETE, PATCH";
    add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept";

But it didn't work...

**Comment by berturion** [comment] 2018-05-18 10:38
If I give you a zip of my nginx conf, would you be able to reproduce this ?

**Comment by marius-wieschollek** [comment] 2018-05-18 11:53
Let me check this later, i think i can reproduce the issue on my development setup

**Comment by berturion** [comment] 2018-05-18 15:11
Hi, thanks for your attention on this :)
Just asking, why using PATCH instead of PUT method for this update request ?

**Comment by berturion** [comment] 2018-05-18 17:14
Ok thank you, I was completely lost in technical readings about request methods in nginx conf ! I just downloaded these builds, I will try to install them right now.

**Comment by berturion** [comment] 2018-05-18 17:28
It works !

**Comment by marius-wieschollek** [comment] 2018-05-19 10:06
Great, then i will close this and release the new plugin version together with either 2018.5.2 or 2018.6.0

**Closed by marius-wieschollek** 2018-05-19 10:06 UTC

**Comment by berturion** [comment] 2018-06-03 07:30
Sorry to bother you @marius-wieschollek but I would like to know when you think of releasing the new versions with this fix please ?

**Comment by marius-wieschollek** [comment] 2018-06-03 07:31
tomorrow

**Comment by berturion** [comment] 2018-06-03 07:51
Great, thanks :)
