### ISSUE TITLE
Crashes/unresponsive since Chrome 104

### ISSUE THREAD

**Issue by barrydegraaff** [marius-wieschollek/passwords-webextension#230] opened 2022-08-04 09:55 UTC
Since updating to Google Chrome 104 the extension crashes (I see a pop-up balloon from Google Chrome), the dialog to search for passwords also is unresponsive most of the time. (Left clicking the extension does not generate the options I usually see) On a different machine running Chrome 103 it still works. Tried removing the extension, remove all browser settings and re-install but issue remains. Sporadically it still works and fills passwords. 

But I used this for a year without issue till 104. And I find myself copy/pasting from Nextcloud UI all the time now.

### System Information
- Extension Version: 2.2.4
- App Version: 2022.6.20
- Browser and Version: Chrome,Version 104.0.5112.79 (Official Build) (64-bit)
- Client OS and Version: Linux Fedora 36

### Steps to reproduce
1. 
2. 
3. 

### Expected result
What should happen?

### Actual result
What does happen?

### Browser log
```
background.js:2 Could not establish connection. Receiving end does not exist.  {details: {…}, error: {…}} Error: Could not establish connection. Receiving end does not exist.
    at I (chrome-extension://mglficilngdmdplbmeacgekicjpkmela/js/background.js:2:742452)
_addError @ background.js:2
logError @ background.js:2
_sendMessage @ background.js:2
await in _sendMessage (async)
_sendMessages @ background.js:2
_messageEnabler @ background.js:2
```

```
In Firefox:
 - Open about:debugging#/runtime/this-firefox
 - Click "Inspect" on the extension
 - Copy the content from the "Console" tab

In Chrome
 - Open chrome://extensions
 - Enable "Developer mode" in the top right corner
 - Click "Background page" on the extension
 - Copy the content from the "Console" tab
```
</details>

**Comment by Riscue** [comment] 2022-08-04 12:29
Same issue.

```
System Information
Extension Version: 2.2.4
App Version: 2022.6.20
Browser and Version: Chrome,Version 104.0.5112.79 (Official Build) (64-bit)
Client OS and Version: Linux Mint 20.1 Cinnamon
```

**Comment by fuse314** [comment] 2022-08-04 20:07
Same in Brave, also since updating to Chromium 104:

My Browser log:
`[server]/index.php/apps/passwords/api/1.0/session/open:1          Failed to load resource: the server responded with a status of 401 ()
background.js:2 HTTP 401 - Unauthorized UnauthorizedError: HTTP 401 - Unauthorized
    at c.getClass (background.js:2:556722)
    at f.getClass (background.js:2:616251)
    at O._getHttpError (background.js:2:573303)
    at O._processJsonResponse (background.js:2:572728)
    at O.send (background.js:2:571261)
    at async K.authorize (background.js:2:575208)
    at async I._attemptManualAuth (background.js:2:765377)
    at async I._tryManualAuth (background.js:2:765017)
    at async I._tryAuthorization (background.js:2:764019)
    at async I.authorize (background.js:2:763745) Object UnauthorizedError: HTTP 401 - Unauthorized
    at c.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:556722)
    at f.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:616251)
    at O._getHttpError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:573303)
    at O._processJsonResponse (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:572728)
    at O.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:571261)
    at async K.authorize (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:575208)
    at async I._attemptManualAuth (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:765377)
    at async I._tryManualAuth (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:765017)
    at async I._tryAuthorization (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:764019)
    at async I.authorize (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:763745)
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2
background.js:2 No tab with id: 735667830. Error: No tab with id: 735667830.
    at background.js:2:739937 Object Error: No tab with id: 735667830.
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937
_addError @ background.js:2`

After enabling extension "Developer mode" (to copy the console text) and closing the original tab where I opened the dialog first, the extension seems to be working again normally.

I have set an E2E encryption passphrase.

**Comment by serpentes80** [comment] 2022-08-05 05:58
same issues here on 3 different computers (win10/win11) since chrome update yesterday

**Comment by DeRaafMedia** [comment] 2022-08-05 14:15
I have same problem. Browser log looks similar to the one given above. I also set E2E encryption.  

Chrome version 104.0.5112.79.
Extension version 2.2.4
Pop!_OS 22.04.

It seems that if I'm already logged in on a website the extension seem to function normal (but not very useful). If I have a page open with login fields the extension seem to crash, or I get a red box telling me that the extension could not paste credentials. It crashes more than getting the red box though.

**Comment by barrydegraaff** [comment] 2022-08-06 05:58
Tried Chromium Version 104.0.5112.79 (Official Build) (64-bit), also Password extension hangs, I am also seeing an 100% CPU load on both Chrome ans Chromium because of Nextcloud Passwords Extension.

**Comment by DeRaafMedia** [comment] 2022-08-06 10:26
> Tried Chromium Version 104.0.5112.79 (Official Build) (64-bit), also Password extension hangs, I am also seeing an 100% CPU load on both Chrome ans Chromium because of Nextcloud Passwords Extension.

I can confirm high CPU usage, I have AMD Ryzen 7 systems, it doesn´t peak at 100% for me, but it's very high on individual cores. 

I tried to login to a wordpress website I had to do some work on. The wordpress login page crashed on me (and the password extension also), can´t say for sure it's related, but I suspect it might be.

**Comment by mrtumnus** [comment] 2022-08-08 17:50
Also seeing this in Brave Version 1.42.88 Chromium: 104.0.5112.81 (Official Build) (64-bit).  I managed to get the extension settings open, and found some errors in the error log:

```
[2022-08-08 14:45:37] Loading chunk 7957 failed. (timeout: chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/PasswordRelated.js)
[2022-08-08 14:45:37] Loading chunk 7957 failed. (timeout: chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/PasswordRelated.js)
[2022-08-08 14:42:15] No tab with id: 1680811420.
[2022-08-08 14:42:15] No tab with id: 1680811420.
...(above error repeated)...
```

**Comment by ruedigerkupper** [comment] 2022-08-08 18:32
Confirming.

**Comment by error420** [comment] 2022-08-08 21:30
Same freezing/unresponsive issue. Tried downgrading to last stable app version "2021.112.20" in Nextcloud and did not lose any data but extension still does not work.

**Comment by stoamandl** [comment] 2022-08-11 08:42
Same with Chrome 104.0.5112.81 on Windows 10 and Edge 104.0.1293.47 with Extension Version 
2.2.4.4461 and NC 24.0.3 Addon API 2022.6

**Comment by XXDoMi77** [comment] 2022-08-11 20:49
Same

**Comment by Schleichmichl** [comment] 2022-08-14 10:05
Same here

**Comment by fuse314** [comment] 2022-08-15 15:17
The behavior is probably connected to this chromium bug: [bugs.chromium.org / 1349787](https://bugs.chromium.org/p/chromium/issues/detail?id=1349787&q=getviews&can=2)

Please use [github reactions](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) on the first post if you want to confirm that you are affected by this issue, too - to avoid notification overflow for all users "watching" this issue.

**Comment by unterweltler** [comment] 2022-08-17 08:46
The chromium bug is fixed with Version `104.0.5112.101`.
But even after the update the Extension still uses 99% CPU and is not usable.

**Comment by serpentes80** [comment] 2022-08-18 06:57
after the update is was working for 1 day.
since then I'm getting the following Error in the Debug log:

`
{
  "details": {
    "data": {
      "module": {},
      "message": {
        "id": "0973f37e-4dcb-46c1-b093-2100c6dd54fd",
        "tab": null,
        "type": "server.reload",
        "reply": null,
        "silent": false,
        "sender": "popup",
        "channel": "runtime",
        "payload": "2e497914-877e-44ca-a9fd-fac7f13c2219",
        "receiver": "background"
      },
      "reply": {
        "id": "2517b590-5437-4f52-9c74-e9cd4bc6bbcc",
        "tab": null,
        "type": null,
        "reply": "0973f37e-4dcb-46c1-b093-2100c6dd54fd",
        "silent": false,
        "sender": "background",
        "channel": "runtime",
        "payload": null,
        "receiver": "popup"
      }
    },
    "message": "Cannot read properties of null (reading 'hasItems')",
    "stack": "TypeError: Cannot read properties of null (reading 'hasItems')\n    at Object.addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:766843)\n    at async Object.reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:767339)\n    at async l.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/ServerReload.js:1:389)\n    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:858044)\n    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:853917)\n    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:816636)\n    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:816223)\n    at async Object._processReceivedMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815271)",
    "time": 1660805766138
  },
  "error": {
    "name": "TypeError",
    "stack": "TypeError: Cannot read properties of null (reading 'hasItems')\n    at Object.addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:766843)\n    at async Object.reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:767339)\n    at async l.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/ServerReload.js:1:389)\n    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:858044)\n    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:853917)\n    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:816636)\n    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:816223)\n    at async Object._processReceivedMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815271)",
    "string": "TypeError: Cannot read properties of null (reading 'hasItems')",
    "message": "Cannot read properties of null (reading 'hasItems')"
  }
}`

Extension isn't able to read a single password from the cloud at the moment

**Comment by marius-wieschollek** [comment] 2022-08-21 13:32
There seems to be a strange behavior of [`for … of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) in this specific case with chrome (see patch above). After all passwords have been fetched from the server, the recommendation manager iterates over an array of all (opened) tabs to update the recommendations. The tabs are stored in the array at the position of their tab id (So if there is one tab with the id 1000, then the array contains a single value at the position 1000).

For whatever reason, chrome now has very high tab ids and will iterate over all empty/nonexisting entries which causes high load and unresponsiveness by the extension.

I have pushed a fix for this behavior and the developer version with it should be published in the chrome web store soon.

**Comment by colpari** [comment] 2022-08-22 09:46
Confirmed working again with the developer-extension - thanks!

Can you estimate when the normal extension will get the update too?

**Comment by barrydegraaff** [comment] 2022-08-22 11:19
I can confirm also that this issue is fixed using the development version.

**Comment by EdRoxter** [comment] 2022-08-22 17:16
> I can confirm also that this issue is fixed using the development version.

Ditto, hoping for it to be released in the stable/main release channel too!

**Comment by barrydegraaff** [comment] 2022-08-23 13:19
Well after 3 weeks of manual copy-pasting I am happy to use the 
development version as a work-around in the mean-time.

**Comment by mrtumnus** [comment] 2022-08-23 14:12
Thanks, @marius-wieschollek !  Developer extension is working great.

For anyone wondering, the developer extension is published separately in the Chrome store, here:
https://chrome.google.com/webstore/detail/aipncmjoigmhooiiclcailmhiopachih

**Comment by marius-wieschollek** [comment] 2022-08-23 18:48
I have pushed the update to the stable release. It should be available for Chrome in the coming days and for edge in the coming weeks.

**Closed** 2022-09-03 08:10 UTC
Labels: bug
