### ISSUE TITLE
100% CPU usage when browser is open 

### ISSUE THREAD

**Issue by jason-m** [marius-wieschollek/passwords-webextension#233] opened 2022-08-11 20:44 UTC
### System Information
- Extension Version: 2.2.4
- App Version: 
- Browser and Version: Vivaldi
- Client OS and Version: 

### Steps to reproduce
1. open browser
2. watch cpu hit 100%

### Expected result
What should happen?
It should use a reasonable amount of CPU some of the time 

### Actual result
Uses an unreasonable amount of CPU all of the time

**Comment by realdarKing** [comment] 2022-08-12 07:27
Happens for me too (uses a single core at 100% right after start) + plugin itself not responsive. Meaning, nothing happens when I click the Key symbol.

This lasts for 5-10 minutes (estimate) then CPU usage drops and extension is responsive again.
No recent update on NC side, so maybe a Chromium / Blink update?

- Extension Version: 2.2.4
- App Version: 2022.6.20
- Chrome 104.0.5112.81
- Windows 10 21h2

**Comment by a7lan** [comment] 2022-08-14 08:02
Same here. Last Vivaldi version.

**Comment by Darneus** [comment] 2022-08-18 08:45
Same here - Brave 1.42.95 (Chromium: 104.0.5112.81)

**Comment by unterweltler** [comment] 2022-08-19 06:39
I think this related to #230

**Comment by marius-wieschollek** [comment] 2022-08-20 15:53
Duplicate of https://github.com/marius-wieschollek/passwords-webextension/issues/230

**Closed by marius-wieschollek** 2022-08-20 15:53 UTC
Labels: bug
