### ISSUE TITLE
Error class model.nullField does not exist when fetching passwords

### ISSUE THREAD

**Issue by fherbet** [marius-wieschollek/passwords-webextension#114] opened 2021-01-04 15:09 UTC
### System Information
- Extension Version: 2.0.0
- App Version: 2020.12.1
- Browser and Version: Mozilla Firefox 84.0.1 
- Client OS and Version: Desktop Win x86-64

### Steps to reproduce
1.  upgrade to FF latest version 2.0.0
2. restart FF
3. no password detected by extension without changing any parameters OR recreating my NC account in the extension 

### Expected result
What should happen?
i can get my passwords and fill credentials boxes

### Actual result
What does happen?
no passwords are detected

### Browser log
<details>
<summary>Browser log</summary>

```
Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    _sendMessage moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1
 
Object { details: {…}, error: {…} }
 _sendMessage@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1:8534
background.js:1:5319
    _addError moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1
    logError moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1
    _sendMessage moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1
The class model.nullField does not exist Error: The class model.nullField does not exist
    getClass moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    getClass moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    fromObject moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    fromArray moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    fromJSON moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    fromObject moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    fromEncryptedData moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    makePasswordFromApiData moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    makeFromApiData moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    _dataToModel moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    _dataToModels moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    _dataToModels moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    _dataToModels moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
    findAll moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14
 
Object { details: {…}, error: {…} }
 getClass@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:114000
getClass@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:151862
fromObject@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123135
fromArray@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123214
fromJSON@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123012
fromObject@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:122249
fromEncryptedData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:121362
makePasswordFromApiData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:140291
makeFromApiData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:139904
_dataToModel@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116770
_dataToModels/</<@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116631
_dataToModels/<@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116610
_dataToModels@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116549
findAll@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116451
background.js:1:5319
    _addError moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1
    logError moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1
    _reloadServer moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:20
```
</details>

### Extension Debug log
<details>
<summary>Extension Debug log</summary>

```
{"details":{"data":{"id":"be59dec6-ea73-4481-a70b-7f7501e35bac","tab":null,"type":"queue.fetch","reply":null,"silent":false,"sender":null,"channel":"runtime","payload":{"name":"mining"},"receiver":"background"},"message":"Could not establish connection. Receiving end does not exist.","file":"moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js","line":1,"stack":"_sendMessage@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1:8534\n","time":1609770702219},"error":{"name":"Error","stack":["_sendMessage@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:1:8534",""],"string":"Error: Could not establish connection. Receiving end does not exist.","fileName":"moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js","lineNumber":1,"columnNumber":8534,"message":"Could not establish connection. Receiving end does not exist."}}



{"details":{"data":{},"message":"The class model.nullField does not exist","file":"moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js","line":14,"stack":"getClass@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:114000\ngetClass@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:151862\nfromObject@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123135\nfromArray@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123214\nfromJSON@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123012\nfromObject@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:122249\nfromEncryptedData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:121362\nmakePasswordFromApiData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:140291\nmakeFromApiData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:139904\n_dataToModel@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116770\n_dataToModels/</<@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116631\n_dataToModels/<@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116610\n_dataToModels@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116549\nfindAll@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116451\n","time":1609770705618},"error":{"name":"Error","stack":["getClass@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:114000","getClass@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:151862","fromObject@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123135","fromArray@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123214","fromJSON@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:123012","fromObject@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:122249","fromEncryptedData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:121362","makePasswordFromApiData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:140291","makeFromApiData@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:139904","_dataToModel@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116770","_dataToModels/</<@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116631","_dataToModels/<@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116610","_dataToModels@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116549","findAll@moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js:14:116451",""],"string":"Error: The class model.nullField does not exist","fileName":"moz-extension://c38ff53e-b34f-4247-80ed-e020de099595/js/background.js","lineNumber":14,"columnNumber":114000,"message":"The class model.nullField does not exist"}}


```
</details>

**Comment by pousterlus** [comment] 2021-01-04 15:59
Hi there,

I encounter the same behavior here. On a webpage where credentials are stored on the nextcloud instance (and I can find them by using the extension search field), there is no option for filling them like it did before.

Extension version : 2.0.0
Firefox version : 84.0.1

-- 
Léo.

**Comment by eskibars** [comment] 2021-01-04 17:33
I also had this happen to me.  This seems to be an issue with the configuration of the server in the extension.  If someone stumbles into this issue and needs a workaround, the following at l did the following steps to resolve.
1. Open your extension settings for Nextcloud passwords in FF
2. Select the "options" tab
3. You should see 1 account there (assuming you have 1 Nextcloud server).  I removed it so that the FF extension thought I was logged out.  (Note: the UX for actually removing the accounts is a bit challenging as well.  By default, you can see a Save icon on the right, but if you click the account header area, you'll see it's actually an accordion-style bar and by collapsing it, you're now given a Delete icon.  It took me a few minutes to navigate to find that this could be done.)
5. Go onto your Nextcloud server and log on
6. I went to `<base Nextcloud server URL>/settings/admin/passwords` and disabled `Enable Legacy API`.  I'm not sure if that was strictly necessary or if there are other clients it would affect but YOLO
6. Go to `<base URL>/apps/passwords/#/apps`.  You should see the Official Firefox Client there.  By selecting that link, it should generate a new link to log in through the extension

**Comment by marius-wieschollek** [comment] 2021-01-04 18:18
Before this spirals out of control: This ticket is only about a bug that is caused by a custom field with the type "null". If you are affected by this error, you will see the error message "The class model.nullField does not exist" in the error log in the debug tab of the extension options.

@pousterlus I'm not entirely sure if i understand the issue you are facing. If you can find credentials with the search in the extension popup, this bug is likely not connected to your issue. If you don't see the error message mentioned above please open a new issue with detailed information on how to reproduce your issue.

@eskibars The ui in step 3 is something i will look into. Step 5 should not be necessary as this api is no longer used. Aside from that, your way should fix most connection issues. See the [wiki](https://github.com/marius-wieschollek/passwords-webextension/wiki#extension-setup) for guides how to connect to the server in any supported browser.

**Comment by pousterlus** [comment] 2021-01-04 19:29
Hi Marius,

I didn't provide many details about the problem I was facing because I assumed I only was doing a +1 :)
But you're right, with the new name of the issue, I discovered the issue wasn't the same for me.
I'll open a separate one.

-- 
Léo.

**Comment by marius-wieschollek** [comment] 2021-01-09 14:27
This issue should now be handled better in the [current nightly](https://github.com/marius-wieschollek/passwords-webextension/wiki/nightly-builds). If it is not possible to parse a custom field or all custom fields, there should be an error notification and more details in the log. All other passwords should work fine.

**Comment by fherbet** [comment] 2021-01-09 17:11
Hi Marius, i just tested nightly extension

here are the results


`{"details":{"data":{"field":{"label":1,"type":null,"value":null},"level":"error"},"message":"Found invalid custom field","file":"moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js","line":1,"stack":"error@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:1:5276\nfromObject@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:123418\nfromArray@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:123664\nfromJSON@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:123241\nfromObject@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:122270\nfromEncryptedData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:121382\nmakePasswordFromApiData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:140743\nmakeFromApiData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:140356\n_dataToModel@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116790\n_dataToModels/</<@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116651\n_dataToModels/<@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116630\n_dataToModels@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116569\nfindAll@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116471\n","time":1610209969038},"error":{"name":"Error","stack":["error@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:1:5276","fromObject@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:123418","fromArray@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:123664","fromJSON@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:123241","fromObject@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:122270","fromEncryptedData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:121382","makePasswordFromApiData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:140743","makeFromApiData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:140356","_dataToModel@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116790","_dataToModels/</<@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116651","_dataToModels/<@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116630","_dataToModels@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116569","findAll@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116471",""],"string":"Error: Found invalid custom field","fileName":"moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js","lineNumber":1,"columnNumber":5276,"message":"Found invalid custom field"}}`


+

`{"details":{"data":{},"message":"this._client is undefined","file":"moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js","line":14,"stack":"fromObject@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:122304\nfromEncryptedData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:121382\nmakePasswordFromApiData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:140743\nmakeFromApiData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:140356\n_dataToModel@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116790\n_dataToModels/</<@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116651\n_dataToModels/<@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116630\n_dataToModels@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116569\nfindAll@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116471\n","time":1610209969077},"error":{"name":"TypeError","stack":["fromObject@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:122304","fromEncryptedData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:121382","makePasswordFromApiData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:140743","makeFromApiData@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:140356","_dataToModel@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116790","_dataToModels/</<@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116651","_dataToModels/<@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116630","_dataToModels@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116569","findAll@moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js:14:116471",""],"string":"TypeError: this._client is undefined","fileName":"moz-extension://002b2931-b960-44b1-97fc-6b8904738f2f/js/background.js","lineNumber":14,"columnNumber":122304,"message":"this._client is undefined"}}`



then i started to think about finding the password i could have with custom fields...
i tried to extract passwords in a CSV but it failed with that message 

> t.value is null

the only way to extract them was to use option 'database save' which outputs a json file...
and i found that there was only one with custom fields..
here's what it looked like : 

`"customFields":[{"label":1,"type":null,"value":null},{"label":"Company Number","type":"text","value":"COL039"}]`


after deleting 1st one which was "null", then extension works with either nightly or official version 2.0.0 (so does csv extract)

hope it helps... !

**Comment by marius-wieschollek** [comment] 2021-01-12 20:32
With the 2.0.1 update of the extension, you should get a warning for affected passwords.
With the 2020.12.2 and 2021.1.1 updates for the passwords app, the affected passwords should be fixed server side if no client side encryption is used.

**Closed by marius-wieschollek** 2021-01-12 20:32 UTC
Labels: bug
